version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
     - db
    ports:
     - "8080:80"
    volumes:
     - ./dist:/var/www/html/wp-content/themes
     - ./db-data:/docker-entrypoint-initdb.d
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: root

  db:
    image: mysql:5.7
    container_name: mysql57
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
     - "13306:3306"
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE: wordpress"
      - "MYSQL_USER: wordpress"
      - "MYSQL_PASSWORD=wordpress"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - "9000:80"
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
volumes:
  db_data: