version: "3"
services:
  python3:
    container_name: python-container
    build: ./python
    ports:
      - "4000:4000"
    volumes:
      - ./python:/app
    tty: true

  nuxt:
    container_name: nuxt-container
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - "8080:3000"
    tty: true
